name: absensi_acara
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^3.0.3

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  rxdart: ^0.28.0

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # QR Code & Scanner
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2

  # Image + HTTP (Tambahan)
  image_picker: ^1.0.7
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/success.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
